### ISSUE TITLE
flac files doesn't show any cover

### ISSUE THREAD

**Issue by legacychimera247** [knuxify/eartag#26]
well i guess the title says it all?as you can see from the screen anyway...
![Schermata del 2022-09-13 02-27-43](https://user-images.githubusercontent.com/22254556/189781813-d5e02c98-22ae-4703-9794-9d9db98cfb65.png)

edit : the same applies for m4a...

**Comment by knuxify** [comment]
Can reproduce this, seems like I missed something when implementing FLAC cover support...
