### ISSUE TITLE
Add icon / symbolic icon

### ISSUE THREAD

**Issue by igor-dyatlov** [knuxify/eartag#3]
For the first version, it would be good to get an icon.

First attempt: Draw a forward value.
A source of inspiration: https://en.wikipedia.org/wiki/Ear_tag

What do you say about this:
![1111](https://user-images.githubusercontent.com/15961107/179417433-8e510707-ad16-4d25-827c-fa6d7ad8c79c.png)

**Comment by knuxify** [comment]
That's really nice! It's pretty much what I initially envisioned, although I think the icon should also include something that more clearly indicates its purpose, like a music note. Something like: 

![image](https://user-images.githubusercontent.com/23167991/179418572-a7d38ccc-a2bc-4656-a3d7-beebcdeabdd3.png)

(excuse the crude sketch. should explain why i didn't make an icon myself :p)

I love the idea of including a barcode. Perhaps we could make it say "Ear Tag", as a bit of an easteregg for anyone who scans it? There seem to be [online generators](https://barcode.tec-it.com/en/?data=eartag) that can generate custom barcodes, including text. Could be something to consider.

Overall, this looks great, good job!

**Comment by igor-dyatlov** [comment]
I've already made an easteregg with a barcode) Just the small resolution of the icon does not allow you to read the code
There is also a easteregg to the first commit 772936dad5ef4776650c4c7347a24796012da976

I'll send you a couple more variants.

**Comment by igor-dyatlov** [comment]
Attempting to do something very simple:
![Preview3](https://user-images.githubusercontent.com/15961107/180658753-92351f9d-f8f2-4066-b317-2bc2197e4a41.png)
With a musical note. The most successful variant:
![Preview5](https://user-images.githubusercontent.com/15961107/180658760-6f8ac5e0-2674-442f-b86b-9f80e950ad58.png)
And just a barcode. It looks untidy. But you can make a matching code pattern, but then it won't be readable
![Preview8](https://user-images.githubusercontent.com/15961107/180658763-4c01a529-cc21-4104-8705-c7ad2aaed166.png)

**Comment by knuxify** [comment]
The music note variant looks great! Feel free to submit a pull request with the icon.

**Comment by igor-dyatlov** [comment]
Ready! I also added _**app.drey.EarTag.Source.svg**_, in case someone wants to make changes.

**Comment by igor-dyatlov** [comment]
I forgot to add `self.props.artists = ['Igor Dyatlov']` to **AboutDialog**, but **AdwAboutWindow** has already been released, so this is a task for the next issues

**Comment by knuxify** [comment]
> I forgot to add self.props.artists = ['Igor Dyatlov'] to AboutDialog,

I'll add that in a separate commit. (I've generally been waiting for the libadwaita 1.2 release before moving to AdwAboutDialog, but yeah, I'm aware that I'll have to move it :p)

Thanks a lot!
