### ISSUE TITLE
M4B files are opened, but not editable

### ISSUE THREAD

**Issue by Haaruun-I** [knuxify/eartag#32]
When you open a m4b file in eartag, it shows up but none of the fields work properly and it cannot save. If you have a second file open, clicking on the m4b file does nothing. My best guess as to why is that `audio/mp4` is included as a valid mime type even when there is no backend to handle it. Not sure if this happens to other though, I'll go through and check with a few of the ones in the `VALID_AUDIO_MIMES` list

Empty m4b file
![image](https://user-images.githubusercontent.com/22063464/190597259-ffc4a621-478a-4ef0-9d7d-c23dd243fce6.png)

m4b file selected, other files info is displayed
![image](https://user-images.githubusercontent.com/22063464/190597421-ee5ff448-b41e-4ef7-8dd2-92cee577a2ec.png)

**Comment by Haaruun-I** [comment]
The only other filetype i could find that has the same issue was m4a.
Also, i mistyped in earlier. Its `audio/mpeg` thats the issue, not `audio/mp4`

**Comment by knuxify** [comment]
Are there any errors printed in the logs?

I suspect this might be the same issue as #27. Could you send the output of the commands I posted in a reply there?

**Comment by Haaruun-I** [comment]
> Are there any errors printed in the logs?

I didnt even know that flatpaks logged out to console at all!
![image](https://user-images.githubusercontent.com/22063464/190636199-7abb93ef-57b5-4256-b1b7-ad5be4bccc8f.png)

That seems to be refering to here, although `os.path` is clearly being imported at the top of the file? The error is also being printed out twice
![image](https://user-images.githubusercontent.com/22063464/190636592-0060fd2d-7466-4c34-bdb3-f9a91169cbb9.png)

**Comment by Haaruun-I** [comment]
Ahh, this seems to have been fixed in ce3d42ca0213333b3748e8f65a2248e5718b4691. Once that commit gets released i'll check again for the bug

**Comment by Haaruun-I** [comment]
Just got the new update, it fixes this problem entirely! thanks
