### ISSUE TITLE
Switch to Gnome 43 runtime

### ISSUE THREAD

**Issue by BirdInFire** [knuxify/eartag#45]
Many app using GTK4 & Libadwaita have finished their migration to the Version 43 of the flatpak's gnome runtime.
Do you think eartag will have too for the new release date of Fedora 37 in 10-25-2022 (mm-dd-aaaa) ?

Thanks

**Comment by knuxify** [comment]
Nope, Flatpak doesn't require a version upgrade to release the update. The commit just didn't get published yet (I just hit the "Publish" button on the build, so it should be updated on Flathub in a few minutes).
