### ISSUE TITLE
Unable to open .m4a files (unsupported file format)

### ISSUE THREAD

**Issue by adarsh1001** [knuxify/eartag#60]
### Describe the issue

Steps to reproduce:
1. Open EarTag.
2. Click "Open a file".
3. Select an .m4a file.
4. Error is thrown:
![Screenshot_2022-12-28_21-36-24](https://user-images.githubusercontent.com/8820038/209840287-59888b3a-1074-4e2f-ba80-a5884d9dd20e.png)

Right clicking on an .m4a file and opening in EarTag doesn't work either, it just opens EarTag without loading the file (although the above error is not thrown in this case).

I've tried working with .mp3 and .flac files as well and they work perfectly without issues. It's only .m4a that doesn't work for me.

### Debugging information

The following is from `journalctl` as the troubleshooting tab does not show this error info:

```shell
plasmashell[9421]: Traceback (most recent call last):
plasmashell[9421]:   File "/app/share/eartag/eartag/file.py", line 129, in load_file
plasmashell[9421]:     _file = eartagfile_from_path(path)
plasmashell[9421]:   File "/app/share/eartag/eartag/file.py", line 68, in eartagfile_from_path
plasmashell[9421]:     raise ValueError(f"Unsupported file format for file {path}")
plasmashell[9421]: ValueError: Unsupported file format for file /home/username/Music/English/Queen - Is this the World We Created.m4a
```

### Additional information

System Info:
1. KDE Plasma: 5.26.4
2. EarTag: 0.3.0 (flatpak)

**Comment by knuxify** [comment]
Looks like your m4a file has a mimetype that Ear Tag doesn't recognize as an m4a file; could you run the following commands and send me the results?

```bash
python3
(this will open an interactive Python prompt)
>>> import magic
>>> print(magic.from_file('/home/username/Music/English/Queen - Is this the World We Created.m4a', mime=True)) # replace the path with the proper path to your file
```

**Comment by adarsh1001** [comment]
The output is `video/mp4`.

This could be because the file was downloaded using `youtube-dl` albeit with the audio-only preset which outputs .m4a. Interestingly though, EasyTag is able to load and edit this. It shows the file type as `MP4/AAC`.
