### ISSUE TITLE
Add buttons to switch between files on the side of the screen

### ISSUE THREAD

**Issue by Verantor** [knuxify/eartag#7]
allow to switch tracks using arrow keys and arrow buttons on the middle side of the screen

**Comment by knuxify** [comment]
Could you elaborate? I'm not entirely sure what you're referring to as tracks:

* If it's "track numbers", and you want to edit them with the arrows that often appear near numeric values - that's a [spin button](https://docs.gtk.org/gtk4/class.SpinButton.html), and I'll consider changing the track number fields to use them.
* If it's "tracks in an album/EP/compilation" - currently Ear Tag can't do this, this is tracked separately in #5

**Comment by Verantor** [comment]
Sorry for the late answer I mean that you can switch between songs in a folder using overlay buttons on the left and right 
![image](https://user-images.githubusercontent.com/56546640/185770855-5e56a1cd-9b66-4734-9e69-a670c378e0db.png)

**Comment by Verantor** [comment]
also sorry for my desing skills

**Comment by knuxify** [comment]
#15 has been merged, which means that multiple file support has been added. This also introduces a sidebar for selecting files:

![image](https://user-images.githubusercontent.com/23167991/186936437-da28c6e7-3fbb-4c5e-9478-a191cb284824.png)

Still, the button idea is quite nice, and could be handy in a mobile view where the sidebar isn't immediately visible.
