### ISSUE TITLE
Drop headerbar.flat?

### ISSUE THREAD

**Issue by jannuary** [knuxify/eartag#9]
Ear Tag has a flat headerbar, which is discouraged since makes it unclear where to drag the window from and cuts off the elements in the scroll view nastily:
![image](https://user-images.githubusercontent.com/27908024/183240210-c3cc9ea9-6ae2-4eb9-b654-091965886b23.png)

I suggest just dropping the .flat style class.

**Comment by knuxify** [comment]
This was also pointed out to me in the This Week in GNOME Matrix, and I fixed it locally but forgot to commit it :p 

I'll push the change in a sec.
